#! /bin/sh
# chkconfig: 2345 99 20
# description: sudden ionospheric disturbance collector

# Author: Richard Marko <rissko@gmail.com>

# /etc/init.d/sidc: start and stop the sidc daemon

NAME='sidc'
DESC=''
DAEMON=/usr/bin/sidc
DAEMON_ARGS='-v'
SIDC_PIDFILE=/var/run/sidc.pid

test -x $DAEMON || DAEMON=/usr/local/bin/sidc
test -x $DAEMON || exit 0

. /etc/rc.d/init.d/functions

do_start() {
	alsactl restore
	sleep 1
	su -c "$DAEMON $DAEMON_ARGS" sidc
	return 0
}
do_stop() {
	killall $DAEMON > /dev/null 2>&1
	return 0
}
case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	do_stop
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac
exit $?
